[package]
name = "hedera"
version = "0.1.0"
edition = "2018"
authors = [
    "Ryan Leckey <ryan@launchbadge.com>"
]

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
default = []
bridge = ["mbox", "libc", "slotmap"]

[dependencies]
# nightly enables various feature toggles and is recommended for security
# asm optimizes the sha2 crate
ed25519-dalek = { version = "0.8.1", default-features = false, features = [ "std", "nightly", "asm", "u64_backend" ] }
rand = "0.5.5"
sha2 = "0.8.0"
hex = "0.3.2"
failure = "0.1.3"
simple_asn1 = "0.2.0"
failure_derive = "0.1.3"
once_cell = { version = "0.1.6", features = [ "parking_lot" ] }
num = "0.2.0"
protobuf = "2.1"
libc = { version = "0.2.43", optional = true }
mbox = { version = "0.5.0", optional = true }
itertools = "0.7.8"
chrono = "0.4.6"
futures = "0.1"
# unstable is required to allow non-copy types in the SlotMap (the `Error` types)
slotmap = { version = "0.3.0", features = [ "unstable" ], optional = true }
parking_lot = "0.6.4"
grpc = { git = "https://github.com/mehcode/grpc-rust.git", rev = "25dd109ba6b243162cf472e39bfb83659f67d518" }

[build-dependencies]
protoc-rust-grpc = "0.6.0"
glob = "0.2.11"

[patch.crates-io]
# Dependency upgrade
# https://github.com/dalek-cryptography/ed25519-dalek/pull/53/commits/a1f23067335b20a11b91e51cfef95f0765dc78f9
ed25519-dalek = { git = "https://github.com/mehcode/ed25519-dalek.git", rev = "ec2ca50c95c415afbd509679f1a31a19ee0e3369" }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
