[package]
name = "hedera"
version = "0.1.1-alpha.0"
description = "Hedera SDK for Rust"
license = "Apache-2.0"
repository = "https://github.com/hashgraph/hedera-sdk-rust"
edition = "2018"
keywords = ["hedera", "sdk"]
authors = [
    "Ryan Leckey <ryan@launchbadge.com>"
]

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
default = []
bridge = ["mbox", "libc", "slotmap"]

[dependencies]
# nightly enables various feature toggles and is recommended for security
# asm optimizes the sha2 crate
ed25519-dalek = { version = "0.8.1", default-features = false, features = [ "std", "nightly", "asm", "u64_backend" ] }
rand = "0.5.5"
sha2 = "0.7.0"
hex = "0.3.2"
failure = "0.1.3"
simple_asn1 = "0.2.0"
failure_derive = "0.1.3"
once_cell = { version = "0.1.6", features = [ "parking_lot" ] }
num = "0.2.0"
protobuf = "2.1"
libc = { version = "0.2.43", optional = true }
mbox = { version = "0.5.0", optional = true }
itertools = "0.7.8"
chrono = "0.4.6"
futures = "0.1"
# unstable is required to allow non-copy types in the SlotMap (the `Error` types)
slotmap = { version = "0.3.0", features = [ "unstable" ], optional = true }
parking_lot = "0.6.4"
grpc = "0.6.0"

[build-dependencies]
protoc-rust-grpc = "0.6.0"
glob = "0.2.11"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
